### ISSUE TITLE
Order of errors in summary does not match order of fields within form

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/apply-for-postgraduate-teacher-training#141]
When trying to submit a form with invalid fields (for example, no information entered), the order of issues in the summary at the top of the page does not match the order of fields below:

![Screen Shot 2019-08-07 at 16 42 30](https://user-images.githubusercontent.com/813383/62637025-9329bc00-b932-11e9-8ce1-400eb4638524.png)

This issue appears on the following pages:

* Personal details
* Contact details

**Comment by chubberlisk** [comment]
Thank you for bringing this to us! We've resolved this in #159.
