### ISSUE TITLE
Multiple errors on a field appear on the same line

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/apply-for-postgraduate-teacher-training#142]
In the following example, the field has two errors:

1. Enter the year you were awarded your degree
2. The year you were awarded your degree must be a number

However, they appear together on the same line (and minus a space between them):

![Screen Shot 2019-08-07 at 16 49 18](https://user-images.githubusercontent.com/813383/62637521-822d7a80-b933-11e9-8eec-8891d8b974bc.png)

(Separately, in this case, we probably need just the one error: _Enter the year you were awarded your degree_)

**Comment by chubberlisk** [comment]
Hi @paulrobertlloyd, thanks for noticing this!

We have since fixed this (#150), with text fields only showing a single error now. See below:

![image](https://user-images.githubusercontent.com/42817036/63352770-9fae0b80-c359-11e9-88c0-d88a5a3a9cf5.png)
