### ISSUE TITLE
Find a nice way to host swagger docs

### ISSUE THREAD

**Issue by heidar** [DFE-Digital/apply-for-postgraduate-teacher-training#16]
There's probably a bunch of ways to do this, if anyone has a favourite, please shout.

We should also move the API specification to its own repository.

**Comment by kjdchapman** [comment]
Found it - you can [link editor.swagger.io with a url parameter](https://editor.swagger.io/?url=https://raw.githubusercontent.com/DFE-Digital/apply-for-postgraduate-teacher-training-api/master/api_spec.yml), we can point that to our github repo.

I'll add a README to the other repo with this?

**Comment by kjdchapman** [comment]
Addressing in https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-api/pull/1

**Comment by heidar** [comment]
Great solution, I think we can close this. :)
