### ISSUE TITLE
Create exception/error alerts

### ISSUE THREAD

**Issue by heidar** [DFE-Digital/apply-for-postgraduate-teacher-training#29]
Email @himal-mandalia, @kjdchapman, and @heidar, or a slack integration (probably worth making a new channel at this point).

Worth checking what Find do in this case.

**Comment by benilovj** [comment]
We use application insights and Sentry.

**Comment by dankmitchell** [comment]
Sentry works out of the box with slack notifications.

We’ve got a custom alert setup with app insights but it’s not great
