### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by kjdchapman** [DFE-Digital/apply-for-postgraduate-teacher-training#3]
Dependabot's been pretty handy for me on other similar work. Is there appetite to use it here?

**Comment by fofr** [comment]
We're using it on our Rails boilerplate app:
https://github.com/DFE-Digital/govuk-rails-boilerplate

Not sure if this app was built on top of that foundation.

**Comment by kjdchapman** [comment]
It wasn't - I think we weren't aware of its existence when we span it up. That's useful as a checklist of stuff for us to add!

**Comment by heidar** [comment]
I think @himal-mandalia has to do this one.

**Comment by himal-mandalia** [comment]
@heidar done: https://app.dependabot.com/accounts/DFE-Digital

**Comment by heidar** [comment]
Thanks! 🚀
