### ISSUE TITLE
Fix randomly failing job in pipeline

### ISSUE THREAD

**Issue by heidar** [DFE-Digital/apply-for-postgraduate-teacher-training#32]
[Build & Setup tends to fail sometimes.](https://dfe-ssp.visualstudio.com/Become-A-Teacher/_build/results?buildId=1973)

Not sure why this happens. One theory is that the pipeline [needs a longer delay while waiting for the database to come up.](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/blob/master/azure-pipelines.yml#L28)

**Comment by himal-mandalia** [comment]
According to someone on Find:

> oh that wait thing was on the docker official documentation...
> 
> basically `web` don't know when `db` is ready
> 
> so it `web` needs to hang around for `db` to be finished with provisioning and ready to accept connections

So we may just have to increase the wait time.
