### ISSUE TITLE
Upgrade PostgreSQL to version 10

### ISSUE THREAD

**Issue by heidar** [DFE-Digital/apply-for-postgraduate-teacher-training#34]
Azure offers PostgreSQL 10 and we are on 9 at the moment, it'd be nice to be on the latest version but not a dealbreaker. It's probably easier to do this now than later.

This is most likely done by passing a parameter in the ARM template.

If we've put the version in the README, remember to update that too.

**Comment by heidar** [comment]
cc @himal-mandalia

**Comment by himal-mandalia** [comment]
Yes, this should be specified as a Postgres version in the `template.json` - @EwanNoble do you know the format to do this? Feel free to do it in a branch and open a PR. We may need to tear down / recreate the DB after.
