### ISSUE TITLE
List of applications from the API is directly under the root

### ISSUE THREAD

**Issue by kjdchapman** [DFE-Digital/apply-for-postgraduate-teacher-training#37]
Recommend putting this under a `resources` key instead, as it'll make it easier to change in the future.

As discussed, [we've put this spec in front of vendors recently](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/pull/33#discussion_r262524564), but once we're iterating on it, we should change this.

**NB: This API's implementation is still in a PR - https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/pull/33 - until that's merged, this Issue is a placeholder.**

**Comment by himal-mandalia** [comment]
This API spec we've sent to vendors is statically defined in https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-api - so this shouldn't stop us from iterating on the API in the application for now.

**Comment by kjdchapman** [comment]
Resolved in https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/commit/e567944464b6503e4ef22a266d95e2789bf2973c, in a second version of this API.
